# Generated by Django 3.2.9 on 2021-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoryes',
            field=models.ManyToManyField(related_name='Categoryes', to='articles.Category'),
        ),
    ]
