# Generated by Django 3.2.9 on 2021-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_post_categoryes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryes',
            field=models.ManyToManyField(related_name='Categoryess', to='articles.Category'),
        ),
    ]
